server:
  port: 8081
  ssl:
    key-store: classpath:soulwinter.site.jks
    key-password: 4ruto3058005z9
    key-store-type: JKS
    key-store-password: 4ruto3058005z9

spring:
  application:
    name: hzl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.92.141/dongji?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 8.130.92.141
    port: 6379
    password: root
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.hzl: debug

markerhub:
  jwt:
    secret: 2023hzl20231010dongji
    expire: 604800  #七天
    header: Authorization


aliyun:
  oss:
    # oss对外服务的访问域名
    endpoint: oss-cn-beijing.aliyuncs.com
    # 访问身份验证中用到用户标识
    accessKeyId: LTAI5tNDknjpUFcXKDYGstHM
    # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    accessKeySecret: gIpO7TErrgcL2yUSSXBk95cpGCmwDI
    # oss的存储空间
    bucketName: huangzelin
    # 上传文件大小(M)
    maxSize: 15
    # 上传文件夹路径前缀
    dir:
      prefix: dongji/images/

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:mapper/*.xml



#fastposter:
#  token: ApfrIzxCoK1DwNZOEJCwlrnv6QZ0PCdv
#  # endpoint: https://poster.prodapi.cn
#  endpoint: http://121.37.235.114:5000
